### ISSUE TITLE
Test files missing in release tarball

### ISSUE THREAD

**Issue by bergmark** [tekul/jose-jwt#13]
The test suite will be disabled in stackage because of this, please send a pull request to re-enable it when this gets fixed. Thanks!
https://github.com/bergmark/blog/blob/master/2016/package-faq.md#test-files-cant-be-found

```
> /tmp/stackage-build8/jose-jwt-0.7.2$ dist/build/tests/tests
tests: tests/jwks.json: openBinaryFile: does not exist (No such file or directory)
```

**Comment by tekul** [comment]
Sorry, my bad :-(. Forgot the new extra source files when removing the aeson-qq dependency.
