### ISSUE TITLE
Secure against invalid curve attack?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tekul/jose-jwt#18]
Is this library protected against the invalid curve attack?

http://blogs.adobe.com/security/2017/03/critical-vulnerability-uncovered-in-json-encryption.html

The attacks the library is secure against should be prominently displayed in the README.md as there has been a few in the last years.

**Comment by tekul** [comment]
Since the library doesn't support elliptic-curve JWEs, I don't think it's vulnerable to this attack.
