### ISSUE TITLE
jose-jwt-0.4 test suite failure

### ISSUE THREAD

**Issue by peti** [tekul/jose-jwt#3]
A complete build log that shows the errors is available at http://hydra.cryp.to/build/578072/nixlog/2/raw.

**Comment by tekul** [comment]
There was a problem with the doctests since they need cprng-aes installed (but it doesn't have to be in the cabal file, hence they pass locally). Hackage doesn't run the tests, and 0.4 installs fine with cabal, so to I thought it'd be OK. I'll release a 0.4.1 version which should fix this.

**Comment by peti** [comment]
Thank you!

**Comment by tekul** [comment]
OK, that's 0.4.1 on hackage. Hopefully that should do do the job. Thanks for keeping me right :).

**Comment by tekul** [comment]
The [Hydra build looks to be OK](http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellngPackages.jose-jwt.x86_64-linux) for 0.4.1, so closing.

**Comment by peti** [comment]
Thanks a lot for the quick fix!
