### ISSUE TITLE
Version 0.9.4 on hackage doesn't build with ghc-9.6

### ISSUE THREAD

**Issue by TristanCacqueray** [tekul/jose-jwt#40]
Hi, would it be possible to get a new version published please?

**Comment by tekul** [comment]
I won't be able to do anything for the next few weeks. Could you clarify what the problem is? Is it something that might be fixed by editing dependency bounds, for example?

**Comment by tekul** [comment]
I've uploaded a new version which has been built by Github CI, so _should_ be Ok (I don't have access to a Haskell dev environment at the moment so haven't been able to build locally). Let me know if it works for you.

**Comment by TristanCacqueray** [comment]
Thanks, 0.9.5 build fine!
