### ISSUE TITLE
Move to 'crypton'

### ISSUE THREAD

**Issue by ocramz** [tekul/jose-jwt#41]
Apparently 'cryptonite' is not actively maintained, and 'crypton' is the new standard.

A number of key networking libraries have switched to 'crypton' already : https://packdeps.haskellers.com/reverse/crypton

It's API-compatible, so this should be just an import renaming chore.

**Comment by ocramz** [comment]
Hi @tekul ! Could you upload a new release so that we may import this new version downstream? Thank you!

**Comment by tekul** [comment]
I've released a `0.10.0` version with the `crypton` dependency.

**Comment by ocramz** [comment]
Thank you!
