### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [tekul/jose-jwt#5]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by tekul** [comment]
Thanks for the advanced notice. I'll look into upgrading when I'm clear on what all the implications are. I had some issues with ExceptT/mtl in the past which made me stick with EitherT where possible.

**Comment by tekul** [comment]
Doh!
