### ISSUE TITLE
jose-jwt-0.6 does not compile

### ISSUE THREAD

**Issue by peti** [tekul/jose-jwt#6]
Citing from http://hydra.cryp.to/build/876114/nixlog/1/raw:

~~~~~~~~
Jose/Types.hs:88:24:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.Format.defaultTimeLocale’,
                             imported from ‘Data.Time.Format’ at Jose/Types.hs:35:1-23
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at Jose/Types.hs:41:23-39
~~~~~~~~~~~

**Comment by tekul** [comment]
Thanks for the report. It seems to be a GHC 7.10 compatibility issue (with time 1.5). It should be fixed in 0.6.1 and I've added 7.10 to the travis build to catch similar issues which might pop up.

**Comment by tekul** [comment]
@peti Is this working now? Nixpkgs seems to be using 0.6.2 but I'm not sure where I can check everything is OK in the nix world...

**Comment by tekul** [comment]
Closing as the latest version appears to be 0.6.2:

http://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.jose-jwt.x86_64-linux
